project_name: filebrowser

env:
  - GO111MODULE=on

gitea_urls:
  api: https://git.auridh.me/api/v1
  download: https://git.auridh.me
  skip_tls_verify: false

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/Auridh/filebrowser/v2/version.Version={{ .Version }} -X github.com/Auridh/filebrowser/v2/version.CommitSHA={{ .ShortCommit }}
    main: main.go
    binary: filebrowser
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - riscv64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  -
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "git.auridh.me/auridh/filebrowser:{{ .Tag }}-amd64"
      - "git.auridh.me/auridh/filebrowser:v{{ .Major }}-amd64"
    extra_files:
      - docker_config.json
      - healthcheck.sh
  -
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "git.auridh.me/auridh/filebrowser:{{ .Tag }}-arm64"
      - "git.auridh.me/auridh/filebrowser:v{{ .Major }}-arm64"
    extra_files:
      - docker_config.json
      - healthcheck.sh
  -
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v6"
    goos: linux
    goarch: arm
    goarm: '6'
    image_templates:
      - "git.auridh.me/auridh/filebrowser:{{ .Tag }}-armv6"
      - "git.auridh.me/auridh/filebrowser:v{{ .Major }}-armv6"
    extra_files:
      - docker_config.json
      - healthcheck.sh
  -
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v7"
    goos: linux
    goarch: arm
    goarm: '7'
    image_templates:
      - "git.auridh.me/auridh/filebrowser:{{ .Tag }}-armv7"
      - "git.auridh.me/auridh/filebrowser:v{{ .Major }}-armv7"
    extra_files:
      - docker_config.json
      - healthcheck.sh

docker_manifests:
  - name_template: "git.auridh.me/auridh/filebrowser:latest"
    image_templates:
      - "git.auridh.me/auridh/filebrowser:{{ .Tag }}-amd64"
      - "git.auridh.me/auridh/filebrowser:{{ .Tag }}-arm64"
      - "git.auridh.me/auridh/filebrowser:{{ .Tag }}-armv7"
  - name_template: "git.auridh.me/auridh/filebrowser:{{ .Tag }}"
    image_templates:
      - "git.auridh.me/auridh/filebrowser:{{ .Tag }}-amd64"
      - "git.auridh.me/auridh/filebrowser:{{ .Tag }}-arm64"
      - "git.auridh.me/auridh/filebrowser:{{ .Tag }}-armv7"
  - name_template: "git.auridh.me/auridh/filebrowser:v{{ .Major }}"
    image_templates:
      - "git.auridh.me/auridh/filebrowser:v{{ .Major }}-amd64"
      - "git.auridh.me/auridh/filebrowser:v{{ .Major }}-arm64"
      - "git.auridh.me/auridh/filebrowser:v{{ .Major }}-armv7"
